# These are supported funding model platforms

github: feezx1
patreon: feezx1
open_collective: feezx1
ko_fi: feezx1
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Raspberry-Pi-Control-Server
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
